CREATE TABLE `stock_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `product_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品名称',
  `product_brand` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品品牌',
  `product_spec` text COLLATE utf8mb4_unicode_ci COMMENT '产品规格',
  `pn_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PN码',
  `material_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '物料编码',
  `major_category` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '大类编码',
  `category_serial_no` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分类序号',
  `category_suffix_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '小码',
  `applicable_device_model` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '适用设备型号',
  `device_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备类型',
  `source_sheet` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '产品分类' COMMENT '来源工作表',
  `source_row_no` int(11) DEFAULT NULL COMMENT '来源Excel行号',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `create_timestamp` bigint(20) NOT NULL COMMENT '创建时间戳',
  `update_timestamp` bigint(20) NOT NULL COMMENT '更新时间戳',
  `is_deleted` bigint(20) DEFAULT '0' COMMENT '逻辑删除标识',
  `status` bigint(20) DEFAULT '1' COMMENT '状态(通用字段)',
  PRIMARY KEY (`id`),
  KEY `ix_stock_category_material_code` (`material_code`),
  KEY `ix_stock_category_pn_code` (`pn_code`),
  KEY `ix_stock_category_major_category` (`major_category`)
) ENGINE=InnoDB AUTO_INCREMENT=821 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存分类表'



CREATE TABLE `stock_in_out_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `row_no` int(11) DEFAULT NULL COMMENT '原始序号',
  `category_id` int(11) DEFAULT NULL COMMENT '分类ID(冗余关联,不加外键约束)',
  `is_outbound` int(11) NOT NULL DEFAULT '0' COMMENT '是否已出库:0-在库,1-已出库',
  `category_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '类别',
  `product_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品类型',
  `product_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品名称',
  `product_brand` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品品牌',
  `product_spec` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '产品规格',
  `product_description` text COLLATE utf8mb4_unicode_ci COMMENT '产品描述',
  `pn_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PN码',
  `material_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '物料编码',
  `serial_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '序列号',
  `target_device_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用于设备类型',
  `target_device_brand` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用于设备品牌',
  `target_device_model` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用于设备型号',
  `major_category` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '大类',
  `usage_scene` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用途/设备挂载说明',
  `document_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '单号',
  `inbound_qty` int(11) DEFAULT NULL COMMENT '入库数量',
  `inbound_date` date DEFAULT NULL COMMENT '入库日期',
  `inbound_room` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '入库机房',
  `storage_location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存放位置',
  `stock_qty` int(11) DEFAULT NULL COMMENT '库存数量',
  `outbound_qty` int(11) DEFAULT NULL COMMENT '领用数量',
  `outbound_date` date DEFAULT NULL COMMENT '领用日期',
  `actual_device_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '领用后设备类型',
  `actual_device_brand` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '领用后设备品牌',
  `actual_device_model` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '领用后设备型号',
  `device_position` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备位置',
  `original_owner_org` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原归属用户单位',
  `target_room` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用于机房',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `expansion_remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '扩容备注',
  `source_sheet` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '出入库明细表' COMMENT '来源工作表',
  `source_row_no` int(11) DEFAULT NULL COMMENT '来源Excel行号',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `create_timestamp` bigint(20) NOT NULL COMMENT '创建时间戳',
  `update_timestamp` bigint(20) NOT NULL COMMENT '更新时间戳',
  `is_deleted` bigint(20) DEFAULT '0' COMMENT '逻辑删除标识',
  `status` bigint(20) DEFAULT '1' COMMENT '状态(通用字段)',
  PRIMARY KEY (`id`),
  KEY `ix_stock_in_out_record_category_id` (`category_id`),
  KEY `ix_stock_in_out_record_is_outbound` (`is_outbound`),
  KEY `ix_stock_in_out_record_document_no` (`document_no`),
  KEY `ix_stock_in_out_record_material_code` (`material_code`),
  KEY `ix_stock_in_out_record_pn_code` (`pn_code`),
  KEY `ix_stock_in_out_record_serial_number` (`serial_number`),
  KEY `ix_stock_in_out_record_inbound_date` (`inbound_date`),
  KEY `ix_stock_in_out_record_outbound_date` (`outbound_date`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存出入库记录表'