"""initial schema

Revision ID: 08800922a0c2
Revises: 
Create Date: 2026-03-30 09:44:23.660003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08800922a0c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='手机号'),
    sa.Column('mail', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='用户编号'),
    sa.Column('seat', sa.String(length=64), nullable=True, comment='座位编号'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='职位'),
    sa.Column('superior', sa.String(length=64), nullable=True, comment='上级'),
    sa.Column('login_type', sa.String(length=64), nullable=True, comment='登录类型:single;many'),
    sa.Column('is_tourist', sa.Integer(), nullable=False, comment='0-游客账户;1-非游客账户'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人id'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人id'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aps_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务id'),
    sa.Column('trigger_type', sa.String(length=16), nullable=False, comment='触发器类型:date;interval;cron'),
    sa.Column('trigger_param', sa.JSON(), nullable=False, comment='触发器参数'),
    sa.Column('task_function_name', sa.String(length=255), nullable=True, comment='任务函数名称'),
    sa.Column('task_function_args', sa.JSON(), nullable=False, comment='任务参数:args'),
    sa.Column('task_function_kwargs', sa.JSON(), nullable=False, comment='任务参数:kwargs'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_inbound_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('inbound_date', sa.Date(), nullable=True, comment='入库日期'),
    sa.Column('major_category', sa.String(length=64), nullable=True, comment='大类'),
    sa.Column('product_type', sa.String(length=64), nullable=True, comment='产品类型'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='产品名称'),
    sa.Column('product_brand', sa.String(length=255), nullable=True, comment='产品品牌'),
    sa.Column('product_spec', sa.String(length=255), nullable=True, comment='产品规格'),
    sa.Column('pn_code', sa.String(length=255), nullable=True, comment='PN码'),
    sa.Column('material_code', sa.String(length=128), nullable=True, comment='物料编码'),
    sa.Column('serial_number', sa.String(length=255), nullable=True, comment='序列号'),
    sa.Column('applicable_device_type', sa.String(length=64), nullable=True, comment='适用设备类型'),
    sa.Column('applicable_device_model', sa.String(length=255), nullable=True, comment='适用设备型号'),
    sa.Column('purchase_order_no', sa.String(length=128), nullable=True, comment='采购单号'),
    sa.Column('inbound_qty', sa.Integer(), nullable=True, comment='入库数量'),
    sa.Column('unit', sa.String(length=32), nullable=True, comment='单位'),
    sa.Column('inbound_room', sa.String(length=128), nullable=True, comment='入库机房'),
    sa.Column('storage_location', sa.String(length=255), nullable=True, comment='存放位置'),
    sa.Column('product_description', sa.Text(), nullable=True, comment='产品描述'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id'),
    comment='库存入库明细表'
    )
    op.create_index('ix_stock_inbound_record_inbound_date', 'stock_inbound_record', ['inbound_date'], unique=False)
    op.create_index('ix_stock_inbound_record_major_category', 'stock_inbound_record', ['major_category'], unique=False)
    op.create_index('ix_stock_inbound_record_material_code', 'stock_inbound_record', ['material_code'], unique=False)
    op.create_index('ix_stock_inbound_record_pn_code', 'stock_inbound_record', ['pn_code'], unique=False)
    op.create_index('ix_stock_inbound_record_product_name', 'stock_inbound_record', ['product_name'], unique=False)
    op.create_index('ix_stock_inbound_record_product_type', 'stock_inbound_record', ['product_type'], unique=False)
    op.create_index('ix_stock_inbound_record_purchase_order_no', 'stock_inbound_record', ['purchase_order_no'], unique=False)
    op.create_index('ix_stock_inbound_record_serial_number', 'stock_inbound_record', ['serial_number'], unique=False)
    op.create_table('stock_outbound_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('outbound_date', sa.Date(), nullable=True, comment='领用日期'),
    sa.Column('product_serial_number', sa.String(length=255), nullable=True, comment='产品序列号'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='产品名称'),
    sa.Column('product_brand', sa.String(length=255), nullable=True, comment='产品品牌'),
    sa.Column('product_spec', sa.String(length=255), nullable=True, comment='产品规格'),
    sa.Column('pn_code', sa.String(length=255), nullable=True, comment='PN码'),
    sa.Column('material_code', sa.String(length=128), nullable=True, comment='物料编码'),
    sa.Column('outbound_qty', sa.Integer(), nullable=True, comment='领用数量'),
    sa.Column('usage_purpose', sa.String(length=255), nullable=True, comment='用途'),
    sa.Column('target_device_serial_number', sa.String(length=255), nullable=True, comment='用于设备序列号'),
    sa.Column('target_room', sa.String(length=128), nullable=True, comment='用于机房'),
    sa.Column('target_device_location', sa.String(length=255), nullable=True, comment='用于设备位置'),
    sa.Column('owner_org', sa.String(length=255), nullable=True, comment='设备归属用户单位'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id'),
    comment='库存出库明细表'
    )
    op.create_index('ix_stock_outbound_record_material_code', 'stock_outbound_record', ['material_code'], unique=False)
    op.create_index('ix_stock_outbound_record_outbound_date', 'stock_outbound_record', ['outbound_date'], unique=False)
    op.create_index('ix_stock_outbound_record_pn_code', 'stock_outbound_record', ['pn_code'], unique=False)
    op.create_index('ix_stock_outbound_record_product_name', 'stock_outbound_record', ['product_name'], unique=False)
    op.create_index('ix_stock_outbound_record_product_serial_number', 'stock_outbound_record', ['product_serial_number'], unique=False)
    op.create_index('ix_stock_outbound_record_target_device_serial_number', 'stock_outbound_record', ['target_device_serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_outbound_record_target_device_serial_number', table_name='stock_outbound_record')
    op.drop_index('ix_stock_outbound_record_product_serial_number', table_name='stock_outbound_record')
    op.drop_index('ix_stock_outbound_record_product_name', table_name='stock_outbound_record')
    op.drop_index('ix_stock_outbound_record_pn_code', table_name='stock_outbound_record')
    op.drop_index('ix_stock_outbound_record_outbound_date', table_name='stock_outbound_record')
    op.drop_index('ix_stock_outbound_record_material_code', table_name='stock_outbound_record')
    op.drop_table('stock_outbound_record')
    op.drop_index('ix_stock_inbound_record_serial_number', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_purchase_order_no', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_product_type', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_product_name', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_pn_code', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_material_code', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_major_category', table_name='stock_inbound_record')
    op.drop_index('ix_stock_inbound_record_inbound_date', table_name='stock_inbound_record')
    op.drop_table('stock_inbound_record')
    op.drop_table('aps_tasks')
    op.drop_table('admin')
    # ### end Alembic commands ###
