"""add admin and aps_tasks tables

Revision ID: a15e3980c17d
Revises: 20260327_1105
Create Date: 2026-03-27 11:10:10.224971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15e3980c17d'
down_revision: Union[str, Sequence[str], None] = '20260327_1105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='手机号'),
    sa.Column('mail', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='用户编号'),
    sa.Column('seat', sa.String(length=64), nullable=True, comment='座位编号'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='职位'),
    sa.Column('superior', sa.String(length=64), nullable=True, comment='上级'),
    sa.Column('login_type', sa.String(length=64), nullable=True, comment='登录类型:single;many'),
    sa.Column('is_tourist', sa.Integer(), nullable=False, comment='0-游客账户;1-非游客账户'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人id'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人id'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aps_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务id'),
    sa.Column('trigger_type', sa.String(length=16), nullable=False, comment='触发器类型:date;interval;cron'),
    sa.Column('trigger_param', sa.JSON(), nullable=False, comment='触发器参数'),
    sa.Column('task_function_name', sa.String(length=255), nullable=True, comment='任务函数名称'),
    sa.Column('task_function_args', sa.JSON(), nullable=False, comment='任务参数:args'),
    sa.Column('task_function_kwargs', sa.JSON(), nullable=False, comment='任务参数:kwargs'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aps_tasks')
    op.drop_table('admin')
    # ### end Alembic commands ###
