"""feat: rbac

Revision ID: b55cce9cc203
Revises: 7f8f9c2d4b11
Create Date: 2026-04-08 09:34:22.188558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55cce9cc203'
down_revision: Union[str, Sequence[str], None] = '7f8f9c2d4b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_admin_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'role_id', name='uq_rbac_admin_role')
    )
    op.create_index(op.f('ix_rbac_admin_roles_admin_id'), 'rbac_admin_roles', ['admin_id'], unique=False)
    op.create_index(op.f('ix_rbac_admin_roles_role_id'), 'rbac_admin_roles', ['role_id'], unique=False)
    op.create_table('rbac_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='权限编码'),
    sa.Column('group_key', sa.String(length=64), nullable=True, comment='分组标识'),
    sa.Column('api_path', sa.String(length=255), nullable=True, comment='接口路径'),
    sa.Column('api_method', sa.String(length=16), nullable=True, comment='请求方法'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序值'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_rbac_permission_code')
    )
    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_rbac_role_permission')
    )
    op.create_index(op.f('ix_rbac_role_permissions_permission_id'), 'rbac_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permissions_role_id'), 'rbac_role_permissions', ['role_id'], unique=False)
    op.create_table('rbac_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='角色编码'),
    sa.Column('is_system', sa.Integer(), nullable=False, comment='是否系统内置角色:0否1是'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), server_default=sa.text('1'), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_rbac_role_code'),
    sa.UniqueConstraint('name', name='uq_rbac_role_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rbac_roles')
    op.drop_index(op.f('ix_rbac_role_permissions_role_id'), table_name='rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_role_permissions_permission_id'), table_name='rbac_role_permissions')
    op.drop_table('rbac_role_permissions')
    op.drop_table('rbac_permissions')
    op.drop_index(op.f('ix_rbac_admin_roles_role_id'), table_name='rbac_admin_roles')
    op.drop_index(op.f('ix_rbac_admin_roles_admin_id'), table_name='rbac_admin_roles')
    op.drop_table('rbac_admin_roles')
    # ### end Alembic commands ###
