version: "3.9"

services:
  zwy-stock-service:
    image: zwy-stock-service:dev  #  docker build -f Dockerfile.dev -t zwy-stock-service:dev .
    container_name: zwy-stock-service
    restart: always
    ports:
      - "5001:5001"
    environment:
      FAST_API_ENV: "dev"    # 部署环境，可覆盖Dockerfile里的development
      TZ: "Asia/Shanghai"
    volumes:
      - /Users/yangyuexiong/Desktop/zwy-stock-service:/srv/zwy-stock-service