# -*- coding: utf-8 -*-
# @Time    : 2026/3/10
# @Author  : yangyuexiong
# @File    : rbac_permissions.py

SUPER_ADMIN_ROLE_NAME = "超级管理员"
SUPER_ADMIN_ROLE_CODE = "super_admin"

DEFAULT_PERMISSION_DEFINITIONS = [
    {
        "name": "RBAC管理",
        "code": "rbac.manage",
        "group_key": "rbac",
        "api_path": "/api/rbac/*",
        "api_method": "*",
        "sort": 10,
        "remark": "可管理角色、权限和授权关系",
    },
    {
        "name": "用户列表",
        "code": "admin.list",
        "group_key": "admin",
        "api_path": "/api/admin/page",
        "api_method": "POST",
        "sort": 20,
        "remark": "查询后台用户列表",
    },
    {
        "name": "用户详情",
        "code": "admin.read",
        "group_key": "admin",
        "api_path": "/api/admin/{admin_id}",
        "api_method": "GET",
        "sort": 21,
        "remark": "查看后台用户详情",
    },
    {
        "name": "创建用户",
        "code": "admin.create",
        "group_key": "admin",
        "api_path": "/api/admin",
        "api_method": "POST",
        "sort": 22,
        "remark": "新增后台用户",
    },
    {
        "name": "编辑用户",
        "code": "admin.update",
        "group_key": "admin",
        "api_path": "/api/admin",
        "api_method": "PUT",
        "sort": 23,
        "remark": "编辑后台用户",
    },
    {
        "name": "禁用用户",
        "code": "admin.disable",
        "group_key": "admin",
        "api_path": "/api/admin",
        "api_method": "DELETE",
        "sort": 24,
        "remark": "禁用后台用户",
    },
    {
        "name": "重置密码",
        "code": "admin.reset_password",
        "group_key": "admin",
        "api_path": "/api/admin/reset_password",
        "api_method": "POST",
        "sort": 25,
        "remark": "重置后台用户密码",
    },
    {
        "name": "上传工单附件",
        "code": "work_order.attachment.upload",
        "group_key": "work_order",
        "api_path": "/api/work-orders/attachments",
        "api_method": "POST",
        "sort": 30,
        "remark": "上传工单附件",
    },
    {
        "name": "创建工单",
        "code": "work_order.create",
        "group_key": "work_order",
        "api_path": "/api/work-orders",
        "api_method": "POST",
        "sort": 31,
        "remark": "创建工单草稿",
    },
    {
        "name": "工单列表",
        "code": "work_order.list",
        "group_key": "work_order",
        "api_path": "/api/work-orders/page",
        "api_method": "POST",
        "sort": 32,
        "remark": "查看工单分页",
    },
    {
        "name": "待审批列表",
        "code": "work_order.pending.list",
        "group_key": "work_order",
        "api_path": "/api/work-orders/pending/page",
        "api_method": "POST",
        "sort": 33,
        "remark": "查看待审批分页",
    },
    {
        "name": "工单详情",
        "code": "work_order.read",
        "group_key": "work_order",
        "api_path": "/api/work-orders/{work_order_id}",
        "api_method": "GET",
        "sort": 34,
        "remark": "查看工单详情",
    },
    {
        "name": "发起工单审批",
        "code": "work_order.submit",
        "group_key": "work_order",
        "api_path": "/api/work-orders/{work_order_id}/submit",
        "api_method": "POST",
        "sort": 35,
        "remark": "发起工单申请",
    },
    {
        "name": "执行审批动作",
        "code": "work_order.approve",
        "group_key": "work_order",
        "api_path": "/api/work-orders/{work_order_id}/approve",
        "api_method": "POST",
        "sort": 36,
        "remark": "工单审批同意/退回",
    },
]

